version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge
volumes:
  mongo-volume: